/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bebidas;

import TelasPrincipais.TelaPrincipalG;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo.heusser
 */
public class ExcluirBebida extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirBebida
     */
    public ExcluirBebida() {
        initComponents();
        this.setTitle("Remover Bebiba");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExcluirBebidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ExcluirNomeBebida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ExcluirComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(415, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        ExcluirBebidas.setText("Excluir");
        ExcluirBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(ExcluirBebidas);
        ExcluirBebidas.setBounds(160, 120, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bebida:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 70, 30);

        ExcluirNomeBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirNomeBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(ExcluirNomeBebida);
        ExcluirNomeBebida.setBounds(110, 20, 250, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 130, 81, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Selecione a Categoria:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 180, 30);

        ExcluirComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cervejas", "Destilados", "Energéticos", "Não Alcoólicos", "Vinhos" }));
        getContentPane().add(ExcluirComboBox);
        ExcluirComboBox.setBounds(260, 70, 100, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExcluirBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBebidasActionPerformed
        if(ExcluirNomeBebida.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Campo Vazio, Complete as Informações, Por Favor!","Alert",JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                String url = "jdbc:mysql://localhost:3306/Bebidas";
                String user = "root";
                String pass = "";

                Connection conn = DriverManager.getConnection(url, user, pass);
                Statement stmt = conn.createStatement(); 
                String Query = "DELETE FROM `"+ExcluirComboBox.getSelectedItem()+"` WHERE Nome = '"+ExcluirNomeBebida.getText()+"'";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Bebida removida com sucesso!");

                ExcluirNomeBebida.setText(null);
        
            }catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_ExcluirBebidasActionPerformed

    private void ExcluirNomeBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirNomeBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirNomeBebidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TelaPrincipalG().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirBebidas;
    private javax.swing.JComboBox<String> ExcluirComboBox;
    private javax.swing.JTextField ExcluirNomeBebida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
