/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logar;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author victor.marcelino
 */
public class EsqueceuSenha extends javax.swing.JFrame {

    /**
     * Creates new form EsqueceuSenha
     */
    public EsqueceuSenha() {
        initComponents();
        this.setTitle("Esqueceu a senha"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        senha = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        Confirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 130));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sua Senha é:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 98, 81, 17);

        senha.setEditable(false);
        getContentPane().add(senha);
        senha.setBounds(109, 98, 164, 25);

        cpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpf.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(cpf);
        cpf.setBounds(107, 11, 166, 25);

        Confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmar);
        Confirmar.setBounds(110, 60, 93, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Insira Seu Cpf:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(8, 14, 89, 17);

        Voltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 60, 87, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-26, -26, 420, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
       if (cpf.getText().isEmpty())  { // Verificação da caixa superior (CPF) esta vazia ou não//
            JOptionPane.showMessageDialog(null, "Cpf Vazio,Complete as Informações, Por Favor!", "Alert", JOptionPane.WARNING_MESSAGE);
        }else { 
        setSize(300, 180 ); // Aumenta o Tamanho da Interface//
        Voltar.setLocation(0, 120); //altera posição do botão voltar//
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários"; 
            String user = "root";   // Conexão com a DataBase //
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários WHERE Cpf = '"+cpf.getText()+"'"; // Comando de Busca no Banco de Dados onde o CPF e colocado na Caixa Superior//
            ResultSet Result = stmt.executeQuery(Query);
            while(Result.next()){
                senha.setText(Result.getString(2)); // Senha = Caixa de Texto Inferior//
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro! Cpf não encontrado"); 
        }
       }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        setVisible(false); // Fecha a Aba//
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsqueceuSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField senha;
    // End of variables declaration//GEN-END:variables
}
