/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dados;
import TelasPrincipais.*;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author victor.marcelino
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    final void filtro() {
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while(Result.next()){
                list.addElement(Result.getString(1));
            }
            List.setModel(list);
             ListaA.setModel(list);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    public Usuarios() {
        initComponents();
        this.setTitle("Usuário");
        filtro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Confirmar = new javax.swing.JButton();
        Usuario = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltarADD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UsuarioE = new javax.swing.JTextField();
        Confirm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SenhaGerenteE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        Confirmar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cpf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        senha1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cpf2 = new javax.swing.JTextField();
        cpfA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        senhaA = new javax.swing.JTextField();
        usuarioA = new javax.swing.JTextField();
        confirmarA = new javax.swing.JButton();
        voltarA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaA = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(588, 327));

        jPanel1.setLayout(null);

        List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ValueChange(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 521, 246);

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(484, 270, 90, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-10, -16, 620, 330);

        jTabbedPane1.addTab("Listagem", jPanel1);

        jPanel2.setLayout(null);

        Confirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(Confirmar);
        Confirmar.setBounds(230, 220, 130, 40);

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(Usuario);
        Usuario.setBounds(190, 70, 240, 30);
        jPanel2.add(password);
        password.setBounds(190, 110, 240, 30);
        jPanel2.add(cpf);
        cpf.setBounds(190, 150, 240, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 50, 80, 70);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 100, 70, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Cpf:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 150, 40, 30);

        voltarADD.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        voltarADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        voltarADD.setText("Voltar");
        voltarADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarADDActionPerformed(evt);
            }
        });
        jPanel2.add(voltarADD);
        voltarADD.setBounds(490, 270, 90, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 320);

        jTabbedPane1.addTab("Adicionar", jPanel2);

        jPanel3.setLayout(null);

        UsuarioE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsuarioE.setForeground(new java.awt.Color(102, 102, 102));
        UsuarioE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioEKeyPressed(evt);
            }
        });
        jPanel3.add(UsuarioE);
        UsuarioE.setBounds(200, 80, 200, 30);

        Confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confirm.setText("Confirmar");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        jPanel3.add(Confirm);
        Confirm.setBounds(240, 203, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Usuário:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 70, 80, 40);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel3.add(Voltar);
        Voltar.setBounds(490, 270, 90, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Senha Gerente:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 140, 140, 50);

        SenhaGerenteE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SenhaGerenteE.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(SenhaGerenteE);
        SenhaGerenteE.setBounds(200, 150, 200, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(-10, -10, 650, 360);

        jTabbedPane1.addTab("Excluir", jPanel3);

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Usuário:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 393, 65, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Senha:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 428, 54, 22);
        jPanel4.add(usuario);
        usuario.setBounds(79, 397, 250, 20);
        jPanel4.add(senha);
        senha.setBounds(74, 432, 260, 20);

        Confirmar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Confirmar1.setText("Confirmar");
        Confirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmar1ActionPerformed(evt);
            }
        });
        jPanel4.add(Confirmar1);
        Confirmar1.setBounds(91, 464, 90, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Cpf:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 363, 33, 22);

        cpf1.setEditable(false);
        jPanel4.add(cpf1);
        cpf1.setBounds(61, 367, 270, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(240, 465, 90, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Usuário:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 393, 65, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Senha:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 428, 54, 22);
        jPanel4.add(usuario1);
        usuario1.setBounds(79, 397, 250, 20);
        jPanel4.add(senha1);
        senha1.setBounds(74, 432, 260, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cpf:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 363, 33, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Senha:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(400, 240, 60, 20);

        cpf2.setEditable(false);
        jPanel4.add(cpf2);
        cpf2.setBounds(61, 367, 270, 20);

        cpfA.setEditable(false);
        cpfA.setMinimumSize(new java.awt.Dimension(25, 20));
        cpfA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfAActionPerformed(evt);
            }
        });
        jPanel4.add(cpfA);
        cpfA.setBounds(50, 240, 140, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Cpf:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 240, 40, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Usuário:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(200, 240, 70, 20);

        senhaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaAActionPerformed(evt);
            }
        });
        jPanel4.add(senhaA);
        senhaA.setBounds(460, 240, 110, 25);

        usuarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAActionPerformed(evt);
            }
        });
        jPanel4.add(usuarioA);
        usuarioA.setBounds(280, 240, 110, 25);

        confirmarA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmarA.setText("Confirmar");
        confirmarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarAActionPerformed(evt);
            }
        });
        jPanel4.add(confirmarA);
        confirmarA.setBounds(200, 270, 100, 25);

        voltarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        voltarA.setText("Voltar");
        voltarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAActionPerformed(evt);
            }
        });
        jPanel4.add(voltarA);
        voltarA.setBounds(490, 270, 90, 25);

        ListaA.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaAValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaA);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 580, 230);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(0, -36, 640, 350);

        jTabbedPane1.addTab("Atualizar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        setVisible(false);
        new TelaPrincipalG().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        if (UsuarioE.getText().isEmpty() || SenhaGerenteE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuário e/ou Senha do Gerente Vazios,Complete as Informações, Por Favor!", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {
            if(SenhaGerenteE.getText().equals("2307")){
                try{
                    String url = "jdbc:mysql://localhost:3306/funcionários";
                    String user = "root";
                    String pass = "";

                    Connection conn = DriverManager.getConnection(url, user, pass);
                    Statement stmt = conn.createStatement();
                    String Query = "DELETE FROM `funcionários` WHERE Usuário = '"+UsuarioE.getText()+"'";
                    stmt.execute(Query);

                    JOptionPane.showMessageDialog(null, "Funcionário Deletado Com Sucesso!");

                }catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, e.toString());
                }
            }else{
                JOptionPane.showMessageDialog(null,"Senha do gerente está incorreta");
            }
        }
    }//GEN-LAST:event_ConfirmActionPerformed

    private void UsuarioEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioEKeyPressed
       // if(evt.getKeyCode() == KeyEvent.VK_ENTER){

        //    Confirmar.requestFocus();
            //try{
              //  String url = "jdbc:mysql://localhost:3306/funcionários";
                //String user = "root";
                //String pass = "";

                //Connection conn = DriverManager.getConnection(url, user, pass);
                //Statement stmt = conn.createStatement();
                //String Query = "DELETE FROM `funcionários` WHERE Usuário = '"+Usuario.getText()+"'";
                //stmt.execute(Query);

                //JOptionPane.showMessageDialog(null, "Funcionário Deletado Com Sucesso!");

           // }catch(SQLException e) {
            //    JOptionPane.showMessageDialog(null, e.toString());
            //}
        //}
    }//GEN-LAST:event_UsuarioEKeyPressed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        if(Usuario.getText().isEmpty() || password.getText().isEmpty() || cpf.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Usuário, Senha ou CPF Vazios,Complete as Informações, Por Favor!","Alert",JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                String url = "jdbc:mysql://localhost:3306/funcionários";
                String user = "root";
                String pass = "";

                Connection conn = DriverManager.getConnection(url, user, pass);
                Statement stmt = conn.createStatement();
                String Query = "INSERT INTO `funcionários` (`Usuário`,`Senha`, `Cpf`) VALUES ('"+Usuario.getText()+"','"+password.getText()+"','"+cpf.getText()+"')";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Funcionário adicionado com sucesso!");

                Usuario.setText(null);
                password.setText(null);
                cpf.setText(null);

            }catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_ConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TelaPrincipalG().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValueChange(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ValueChange
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários WHERE Usuário = '"+List.getSelectedValue()+"';";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while(Result.next()){
                //Usuario.setText(Result.getString(1));
                //Acesso.setText(Result.getString(2));
            }
            List.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        filtro();
    }//GEN-LAST:event_ValueChange

    private void Confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmar1ActionPerformed
        try{
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "UPDATE funcionários SET Usuário = '"+usuario.getText()+"',Senha = '"+senha.getText()+"',Cpf = '"+cpf.getText()+"' WHERE Cpf = '"+cpf.getText()+"'";
            stmt.execute(Query);

            JOptionPane.showMessageDialog(null, "Atualizado!");

        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        filtro();
    }//GEN-LAST:event_Confirmar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void senhaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaAActionPerformed

    private void voltarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAActionPerformed
        setVisible(false);
        new TelaPrincipalG().setVisible(true);
    }//GEN-LAST:event_voltarAActionPerformed

    private void confirmarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarAActionPerformed
       try{
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "UPDATE funcionários SET Usuário = '"+usuarioA.getText()+"',Senha = '"+senhaA.getText()+"',Cpf = '"+cpfA.getText()+"' WHERE Cpf = '"+cpfA.getText()+"'";
            stmt.execute(Query);
            
            JOptionPane.showMessageDialog(null, "Atualizado!");

        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        filtro();                                         

    }//GEN-LAST:event_confirmarAActionPerformed

    private void cpfAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAActionPerformed

    private void usuarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioAActionPerformed

    private void ListaAValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaAValueChanged
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários WHERE Usuário = '"+ListaA.getSelectedValue()+"';";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while(Result.next()){
                usuarioA.setText(Result.getString(1));
                senhaA.setText(Result.getString(2));
                cpfA.setText(Result.getString(3));
            }
            ListaA.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        filtro();
    }//GEN-LAST:event_ListaAValueChanged

    private void voltarADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarADDActionPerformed
       setVisible(false);  
        new TelaPrincipalG().setVisible(true);        
    }//GEN-LAST:event_voltarADDActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Confirmar1;
    private javax.swing.JList<String> List;
    private javax.swing.JList<String> ListaA;
    private javax.swing.JTextField SenhaGerenteE;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextField UsuarioE;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton confirmarA;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField cpf1;
    private javax.swing.JTextField cpf2;
    private javax.swing.JTextField cpfA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField password;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senha1;
    private javax.swing.JTextField senhaA;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    private javax.swing.JTextField usuarioA;
    private javax.swing.JButton voltarA;
    private javax.swing.JButton voltarADD;
    // End of variables declaration//GEN-END:variables

    
        }