/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dados;
import TelasPrincipais.*;
import javax.swing.*;
import java.sql.*;


/**
 *
 * @author victor.marcelino
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    final void Usu() {
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while (Result.next()) {
                list.addElement("");
                list.addElement("Usuário: "+Result.getString(1));
                list.addElement("Cpf: "+Result.getString(3));
                list.addElement("");
                list.addElement("");
                list.addElement("");
            }
            ListaFuncionarios.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha ao carregar lista do histórico\n"
                    +"Erro: "+e.toString());
        }
    }
    final void filtro() {
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while (Result.next()) {
                list.addElement("");
                list.addElement(Result.getString(1));
                list.addElement(Result.getString(3));
                list.addElement("");
                list.addElement("");
                list.addElement("");
            }
            ListaAtualizar.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha ao carregar lista do histórico\n"
                    +"Erro: "+e.toString());
        }
    }
    public Usuarios() {
        initComponents();
        this.setTitle("Usuário");
        Usu();
        filtro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JList<>();
        VoltarListagem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ConfirmarAdicionar = new javax.swing.JButton();
        UsuarioAdicionar = new javax.swing.JTextField();
        SenhaAdicionar = new javax.swing.JTextField();
        cpfAdicionar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltarAdicionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CpfExcluir = new javax.swing.JTextField();
        ConfirmarExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        VoltarExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SenhaGerenteExcluir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        Confirmar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cpf1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        senha1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cpf2 = new javax.swing.JTextField();
        cpfAtualizar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        senhaAtualizar = new javax.swing.JTextField();
        usuarioAtualizar = new javax.swing.JTextField();
        confirmarAtualizar = new javax.swing.JButton();
        voltarAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaAtualizar = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(588, 327));

        jPanel1.setLayout(null);

        ListaFuncionarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ValueChange(evt);
            }
        });
        jScrollPane1.setViewportView(ListaFuncionarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 521, 246);

        VoltarListagem.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        VoltarListagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        VoltarListagem.setText("Voltar");
        VoltarListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarListagemActionPerformed(evt);
            }
        });
        jPanel1.add(VoltarListagem);
        VoltarListagem.setBounds(484, 270, 90, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-10, -16, 620, 370);

        jTabbedPane1.addTab("Listagem", jPanel1);

        jPanel2.setLayout(null);

        ConfirmarAdicionar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ConfirmarAdicionar.setText("Confirmar");
        ConfirmarAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAdicionarActionPerformed(evt);
            }
        });
        jPanel2.add(ConfirmarAdicionar);
        ConfirmarAdicionar.setBounds(230, 220, 130, 40);

        UsuarioAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdicionarActionPerformed(evt);
            }
        });
        jPanel2.add(UsuarioAdicionar);
        UsuarioAdicionar.setBounds(190, 70, 240, 30);
        jPanel2.add(SenhaAdicionar);
        SenhaAdicionar.setBounds(190, 110, 240, 30);
        jPanel2.add(cpfAdicionar);
        cpfAdicionar.setBounds(190, 150, 240, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 50, 80, 70);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 100, 70, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Cpf:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 150, 40, 30);

        voltarAdicionar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        voltarAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        voltarAdicionar.setText("Voltar");
        voltarAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAdicionarActionPerformed(evt);
            }
        });
        jPanel2.add(voltarAdicionar);
        voltarAdicionar.setBounds(490, 270, 90, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 350);

        jTabbedPane1.addTab("Adicionar", jPanel2);

        jPanel3.setLayout(null);

        CpfExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CpfExcluir.setForeground(new java.awt.Color(102, 102, 102));
        CpfExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CpfExcluirKeyPressed(evt);
            }
        });
        jPanel3.add(CpfExcluir);
        CpfExcluir.setBounds(200, 80, 200, 30);

        ConfirmarExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ConfirmarExcluir.setText("Confirmar");
        ConfirmarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(ConfirmarExcluir);
        ConfirmarExcluir.setBounds(240, 203, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cpf:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 70, 80, 40);

        VoltarExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        VoltarExcluir.setText("Voltar");
        VoltarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(VoltarExcluir);
        VoltarExcluir.setBounds(490, 270, 90, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Senha Gerente:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 140, 140, 50);

        SenhaGerenteExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SenhaGerenteExcluir.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(SenhaGerenteExcluir);
        SenhaGerenteExcluir.setBounds(200, 150, 200, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(-10, -10, 650, 420);

        jTabbedPane1.addTab("Excluir", jPanel3);

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Usuário:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 393, 65, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Senha:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 428, 54, 22);
        jPanel4.add(usuario);
        usuario.setBounds(79, 397, 250, 20);
        jPanel4.add(senha);
        senha.setBounds(74, 432, 260, 20);

        Confirmar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Confirmar1.setText("Confirmar");
        Confirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirmar1ActionPerformed(evt);
            }
        });
        jPanel4.add(Confirmar1);
        Confirmar1.setBounds(91, 464, 90, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Cpf:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 363, 33, 22);

        cpf1.setEditable(false);
        jPanel4.add(cpf1);
        cpf1.setBounds(61, 367, 270, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(240, 465, 90, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Usuário:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 393, 65, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Senha:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 428, 54, 22);
        jPanel4.add(usuario1);
        usuario1.setBounds(79, 397, 250, 20);
        jPanel4.add(senha1);
        senha1.setBounds(74, 432, 260, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Cpf:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 363, 33, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Senha:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(400, 240, 60, 20);

        cpf2.setEditable(false);
        jPanel4.add(cpf2);
        cpf2.setBounds(61, 367, 270, 20);

        cpfAtualizar.setEditable(false);
        cpfAtualizar.setMinimumSize(new java.awt.Dimension(25, 20));
        cpfAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(cpfAtualizar);
        cpfAtualizar.setBounds(50, 240, 140, 25);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Cpf:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 240, 40, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Usuário:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(200, 240, 70, 20);

        senhaAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(senhaAtualizar);
        senhaAtualizar.setBounds(460, 240, 110, 25);

        usuarioAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(usuarioAtualizar);
        usuarioAtualizar.setBounds(280, 240, 110, 25);

        confirmarAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmarAtualizar.setText("Confirmar");
        confirmarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(confirmarAtualizar);
        confirmarAtualizar.setBounds(200, 270, 100, 25);

        voltarAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/curve-arrow (1).png"))); // NOI18N
        voltarAtualizar.setText("Voltar");
        voltarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAtualizarActionPerformed(evt);
            }
        });
        jPanel4.add(voltarAtualizar);
        voltarAtualizar.setBounds(490, 270, 90, 25);

        ListaAtualizar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaAtualizarValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaAtualizar);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 580, 230);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosenac/Imagens/design-de-plano-de-fundo-texturizado-simples-cinza_53876-63604.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(0, -46, 640, 410);

        jTabbedPane1.addTab("Atualizar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarExcluirActionPerformed
        setVisible(false);
        new TelaPrincipalG().setVisible(true);
    }//GEN-LAST:event_VoltarExcluirActionPerformed

    private void ConfirmarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarExcluirActionPerformed
        if (CpfExcluir.getText().isEmpty() || SenhaGerenteExcluir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuário e/ou Senha do Gerente Vazios,Complete as Informações, Por Favor!", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {
            if (SenhaGerenteExcluir.getText().equals("2307")) {
                try {
                    String url = "jdbc:mysql://localhost:3306/funcionários";
                    String user = "root";
                    String pass = "";

                    Connection conn = DriverManager.getConnection(url, user, pass);
                    Statement stmt = conn.createStatement();
                    String Query = "DELETE FROM `funcionários` WHERE Cpf = '" + CpfExcluir.getText() + "'";
                    stmt.execute(Query);

                    JOptionPane.showMessageDialog(null, "Funcionário Deletado Com Sucesso!");

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Falha ao excluir funcionário\n"
                            +"Erro: "+e.toString());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha do gerente está incorreta");
            }
        }
        filtro();
        Usu();
    }//GEN-LAST:event_ConfirmarExcluirActionPerformed

    private void CpfExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpfExcluirKeyPressed

    }//GEN-LAST:event_CpfExcluirKeyPressed

    private void UsuarioAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAdicionarActionPerformed

    private void ConfirmarAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarAdicionarActionPerformed
        if (UsuarioAdicionar.getText().isEmpty() || SenhaAdicionar.getText().isEmpty() || cpfAdicionar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuário, Senha ou CPF Vazios,Complete as Informações, Por Favor!", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                String url = "jdbc:mysql://localhost:3306/funcionários";
                String user = "root";
                String pass = "";

                Connection conn = DriverManager.getConnection(url, user, pass);
                Statement stmt = conn.createStatement();
                String Query = "INSERT INTO `funcionários` (`Usuário`,`Senha`, `Cpf`) VALUES ('" + UsuarioAdicionar.getText() + "','" + SenhaAdicionar.getText() + "','" + cpfAdicionar.getText() + "')";
                stmt.execute(Query);
                JOptionPane.showMessageDialog(null, "Funcionário adicionado com sucesso!");

                UsuarioAdicionar.setText(null);
                SenhaAdicionar.setText(null);
                cpfAdicionar.setText(null);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Falha ao adicionar funcionário\n"
                        +"Erro: "+e.toString());
            }
        }
        filtro();
        Usu();
    }//GEN-LAST:event_ConfirmarAdicionarActionPerformed

    private void VoltarListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarListagemActionPerformed
        new TelaPrincipalG().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_VoltarListagemActionPerformed

    private void ValueChange(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ValueChange
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários WHERE Usuário = '" + ListaFuncionarios.getSelectedValue() + "';";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while (Result.next()) {
                //Usuario.setText(Result.getString(1));
                //Acesso.setText(Result.getString(2));
            }
            ListaFuncionarios.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro: "+e.toString());
        }
        filtro();
        Usu();
    }//GEN-LAST:event_ValueChange

    private void Confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirmar1ActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "UPDATE funcionários SET Usuário = '" + usuario.getText() + "',Senha = '" + senha.getText() + "',Cpf = '" + cpfAdicionar.getText() + "' WHERE Cpf = '" + cpfAdicionar.getText() + "'";
            stmt.execute(Query);

            JOptionPane.showMessageDialog(null, "Atualizado!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha ao atualizar funcionários \n"+
                    "Erro: "+e.toString());
        }
        filtro();
        Usu();
    }//GEN-LAST:event_Confirmar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void senhaAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaAtualizarActionPerformed

    private void voltarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAtualizarActionPerformed
        setVisible(false);
        new TelaPrincipalG().setVisible(true);
    }//GEN-LAST:event_voltarAtualizarActionPerformed

    private void confirmarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarAtualizarActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "UPDATE funcionários SET Usuário = '" + usuarioAtualizar.getText() + "',Senha = '" + senhaAtualizar.getText() + "',Cpf = '" + cpfAtualizar.getText() + "' WHERE Cpf = '" + cpfAtualizar.getText() + "'";
            stmt.execute(Query);

            JOptionPane.showMessageDialog(null, "Atualizado!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Falha ao atualizar funcionários \n"
                    + "Erro: "+e.toString());
        }
        filtro();
        Usu();
    }//GEN-LAST:event_confirmarAtualizarActionPerformed

    private void cpfAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAtualizarActionPerformed

    private void usuarioAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioAtualizarActionPerformed

    private void ListaAtualizarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaAtualizarValueChanged
        try {
            String url = "jdbc:mysql://localhost:3306/funcionários";
            String user = "root";
            String pass = "";

            Connection conn = DriverManager.getConnection(url, user, pass);
            Statement stmt = conn.createStatement();
            String Query = "SELECT * FROM funcionários WHERE Cpf = '" + ListaAtualizar.getSelectedValue() + "';";
            ResultSet Result = stmt.executeQuery(Query);
            DefaultListModel list = new DefaultListModel();
            while (Result.next()) {
                usuarioAtualizar.setText(Result.getString(1));
                senhaAtualizar.setText(Result.getString(2));
                cpfAtualizar.setText(Result.getString(3));
            }
            ListaAtualizar.setModel(list);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro: "+e.toString());
        }
        filtro();
        Usu();
    }//GEN-LAST:event_ListaAtualizarValueChanged

    private void voltarAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAdicionarActionPerformed
       setVisible(false);  
        new TelaPrincipalG().setVisible(true);        
    }//GEN-LAST:event_voltarAdicionarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar1;
    private javax.swing.JButton ConfirmarAdicionar;
    private javax.swing.JButton ConfirmarExcluir;
    private javax.swing.JTextField CpfExcluir;
    private javax.swing.JList<String> ListaAtualizar;
    private javax.swing.JList<String> ListaFuncionarios;
    private javax.swing.JTextField SenhaAdicionar;
    private javax.swing.JTextField SenhaGerenteExcluir;
    private javax.swing.JTextField UsuarioAdicionar;
    private javax.swing.JButton VoltarExcluir;
    private javax.swing.JButton VoltarListagem;
    private javax.swing.JButton confirmarAtualizar;
    private javax.swing.JTextField cpf1;
    private javax.swing.JTextField cpf2;
    private javax.swing.JTextField cpfAdicionar;
    private javax.swing.JTextField cpfAtualizar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField senha1;
    private javax.swing.JTextField senhaAtualizar;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario1;
    private javax.swing.JTextField usuarioAtualizar;
    private javax.swing.JButton voltarAdicionar;
    private javax.swing.JButton voltarAtualizar;
    // End of variables declaration//GEN-END:variables

    
        }